# Generated by Django 2.2.2 on 2019-07-07 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('prim_key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20)),
                ('name', models.CharField(max_length=50, verbose_name='Your name')),
                ('surname', models.CharField(max_length=50, verbose_name='Your surname')),
                ('mobile_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=75)),
                ('adres', models.CharField(max_length=300)),
                ('date', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2)),
                ('time', models.CharField(choices=[('10:00 - 13:00', '10:00 - 13:00'), ('11:00 - 14:00', '11:00 - 14:00'), ('12:00 - 15:00', '12:00 - 15:00'), ('13:00 - 16:00', '13:00 - 16:00'), ('14:00 - 17:00', '14:00 - 17:00'), ('15:00 - 18:00', '15:00 - 18:00'), ('16:00 - 19:00', '16:00 - 19:00'), ('17:00 - 20:00', '17:00 - 20:00'), ('18:00 - 21:00', '18:00 - 21:00'), ('19:00 - 22:00', '19:00 - 22:00'), ('20:00 - 22:30', '20:00 - 22:30')], max_length=13)),
                ('time_of_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('product', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderNoDel',
            fields=[
                ('prim_key', models.BigIntegerField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=4)),
                ('name', models.CharField(max_length=50, verbose_name='Your name')),
                ('surname', models.CharField(max_length=50, verbose_name='Your surname')),
                ('mobile_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=75)),
                ('time_of_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('product', models.CharField(max_length=300)),
            ],
        ),
    ]
