# Generated by Django 2.2.2 on 2019-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190707_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdelivery',
            old_name='prim_key',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ordernodel',
            old_name='prim_key',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='product',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ordernodel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordernodel',
            name='product',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
