# Generated by Django 2.2.2 on 2019-06-10 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190610_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='book_genre',
        ),
        migrations.AlterField(
            model_name='autors',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='autor name'),
        ),
        migrations.AlterField(
            model_name='autors',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='autor surname'),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 6, 10, 19, 55, 27, 816998)),
        ),
    ]
