# Generated by Django 2.2.2 on 2019-06-11 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20190610_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 6, 11, 18, 26, 4, 215763)),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
