# Generated by Django 2.2.2 on 2019-06-16 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20190612_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 6, 16, 23, 12, 47, 218186)),
        ),
    ]
