# Generated by Django 2.2.2 on 2019-06-17 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20190617_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 6, 17, 13, 42, 53, 696154)),
        ),
    ]
