# Generated by Django 2.2.2 on 2019-06-30 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_auto_20190624_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 6, 30, 19, 29, 34, 706232)),
        ),
    ]
