# Generated by Django 2.2.2 on 2019-07-02 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_auto_20190630_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 2, 20, 18, 56, 719899)),
        ),
    ]
