# Generated by Django 2.2.2 on 2019-07-03 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_auto_20190702_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 3, 23, 41, 52, 310230)),
        ),
    ]
