# Generated by Django 2.2.2 on 2019-07-04 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_auto_20190703_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 4, 22, 18, 1, 95164)),
        ),
    ]
