# Generated by Django 2.2.2 on 2019-07-06 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0024_auto_20190706_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 6, 21, 38, 56, 738598)),
        ),
    ]
