# Generated by Django 2.2.2 on 2019-07-06 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0026_auto_20190706_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 6, 22, 19, 36, 506815)),
        ),
    ]
