# Generated by Django 2.2.2 on 2019-07-06 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0028_auto_20190706_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 6, 23, 41, 30, 141296)),
        ),
    ]
