# Generated by Django 2.2.2 on 2019-07-07 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0029_auto_20190706_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 14, 27, 44, 917512)),
        ),
    ]
