# Generated by Django 2.2.2 on 2019-07-07 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0034_auto_20190707_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 16, 32, 36, 605710)),
        ),
    ]
