# Generated by Django 2.2.2 on 2019-07-07 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0035_auto_20190707_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 21, 53, 28, 281840)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_review', models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 21, 53, 28, 286201))),
                ('author', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=5000)),
                ('book', models.ForeignKey(on_delete='PROTECT', to='bookstore.Book')),
            ],
        ),
    ]
