# Generated by Django 2.2.2 on 2019-07-07 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0036_auto_20190707_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 21, 54, 40, 755249)),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100, null=TabError),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(null=True, on_delete='PROTECT', to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_review',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 21, 54, 40, 759498), null=True),
        ),
    ]
