# Generated by Django 2.2.2 on 2019-07-07 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0038_auto_20190707_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 23, 39, 45, 371014)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_review',
            field=models.DateTimeField(auto_created=datetime.datetime(2019, 7, 7, 23, 39, 45, 375154)),
        ),
    ]
